[[frames]]
width = 64
height = 64
x = 0
y = 0
[[frames]]
width = 64
height = 64
x = 64
y = 0
[[frames]]
width = 64
height = 64
x = 128
y = 0
[[frames]]
width = 64
height = 64
x = 192
y = 0
[[frames]]
width = 64
height = 64
x = 256
y = 0
[[frames]]
width = 64
height = 64
x = 320
y = 0
[[frames]]
width = 64
height = 64
x = 384
y = 0
[[frames]]
width = 64
height = 64
x = 448
y = 0
[[frames]]
width = 64
height = 64
x = 512
y = 0

[animations]
    [animations.idle]
        loop = true
        frames = [0, 1, 2, 3, 4]
    [animations.run]
        loop = true
        frames = [0, 1, 2, 3, 4]
    [animations.shoot]
        loop = true
        frames = [0, 1, 2, 3, 4]