[[frames]]
width = 16
height = 16
x = 0
y = 0
[[frames]]
width = 16
height = 16
x = 16
y = 0
[[frames]]
width = 16
height = 16
x = 32
y = 0
[[frames]]
width = 16
height = 16
x = 48
y = 0
[[frames]]
width = 16
height = 16
x = 64
y = 0
[[frames]]
width = 16
height = 16
x = 80
y = 0

[animations]
    [animations.idle]
        loop = true
        frames = [0, 1 , 2, 1]
    [animations.run]
        loop = true
        frames = [3, 4, 5]
