animation_speed = 0.1
frames = [
    "walk_1.png",
    "walk_2.png",
    "walk_3.png",
    "walk_4.png",
    "walk_5.png",
    "walk_6.png",
    "walk_7.png",
    "walk_8.png",
    "walk_9.png",
    "walk_10.png",
]