animation_speed = 0.1
frames = [
    "sprites/characters/neuro/walk_1.nrs",
    "sprites/characters/neuro/walk_2.nrs",
    "sprites/characters/neuro/walk_3.nrs",
    "sprites/characters/neuro/walk_4.nrs",
    "sprites/characters/neuro/walk_5.nrs",
    "sprites/characters/neuro/walk_6.nrs",
    "sprites/characters/neuro/walk_7.nrs",
    "sprites/characters/neuro/walk_8.nrs",
    "sprites/characters/neuro/walk_9.nrs",
    "sprites/characters/neuro/walk_10.nrs",
]